export const TYPES = {
  AuthController: Symbol.for("AuthController"),
  ImageController: Symbol.for("ImageController"),
  NotificationController: Symbol.for("NotificationController"),
  UserRepository: Symbol.for("UserRepository"),
  UserService: Symbol.for("UserService"),
  ImageRepository: Symbol.for("ImageRepository"),
  ImageService: Symbol.for("ImageService"),
  MessageRepository: Symbol.for("MessageRepository"),
  MessageService: Symbol.for("MessageService"),
  PollRepository: Symbol.for("PollRepository"),
  PollService: Symbol.for("PollService"),
  MessageNotificationRepository: Symbol.for("MessageNotificationRepository"),
  PollNotificationRepository: Symbol.for("PollNotificationRepository"),
  NotificationService: Symbol.for("NotificationService"),
};
